### PR TITLE
Kadir Dev to Main

### PR DESCRIPTION
**Pull request by kadirgokhann**
Includes some improvements and I made some codes more readable

### CODE REVIEW

**Review by kadirgokhann — COMMENTED** [review]
LGTM

**Review by kadirgokhann — COMMENTED** [review]
LGTM

**Review by caglakahriman — APPROVED** [review]
Nice work!!

**Review by kayrakirimli — APPROVED** [review]
Good updates, especially the thread based loading bars looks cool!

**Pull request merged**
